spring:
  ssl:
    bundle:
      jks:
        client:
          keystore:
            location: "classpath:client.p12"
            password: "changeit"
            type: "PKCS12"
          truststore:
            location: "classpath:client-truststore.p12"
            password: "changeit"